In [ ]:
#Extracted from https://www.investing.com/commodities/us-corn-historical-data

In [8]:
import pandas as pd
import datetime

#Clean import oil_price_index_2015_oecd

# Read the data from the weather file
df_futures_corn = pd.read_csv('futures_data/US Corn Futures Historical Data.csv')

# Rename the 'date' column to 'TIME_PERIOD'
df_futures_corn.rename(columns={'Date': 'TIME_PERIOD', 'Price': 'Corn Price Futures'}, inplace=True)

df_futures_corn['TIME_PERIOD'] = pd.to_datetime(df_futures_corn['TIME_PERIOD'], format='%d/%m/%Y')
df_futures_corn['TIME_PERIOD'] = df_futures_corn['TIME_PERIOD'].dt.strftime('%Y/%m/%d')

df_futures_corn.drop(columns=['Open','High','Low','Vol.','Change %'], inplace=True)

df_futures_corn

    TIME_PERIOD  Corn Price Futures
0    2022/01/10              691.50
1    2022/01/09              677.50
2    2022/01/08              673.75
3    2022/01/07              616.25
4    2022/01/06              743.75
..          ...                 ...
208  2005/01/06              222.25
209  2005/01/05              230.75
210  2005/01/04              213.50
211  2005/01/03              221.00
212  2005/01/02              222.75

[213 rows x 2 columns]